{% set name = "clang-format-docs" %}
{% set name_underscore = "clang_format_docs" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name_underscore }}-{{ version }}.tar.gz"
  sha256: a9153ed21d4967a2f848e47e10cd48f1ad1f866415c606850cec46e7392f64c2

build:
  number: 0
  noarch: python
  entry_points:
    - "clang-format-docs=clang_format_docs:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - clang-format
test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-cov

  imports:
    - clang_format_docs

  source_files:
    - tests/
    - pyproject.toml

  commands:
    - clang-format-docs --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/finsberg/clang-format-docs
  summary: Run `clang-format` on C++ code blocks in documentation files
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_blacken_docs
  doc_url: https://finsberg.github.io/clang-format-docs/
  dev_url: https://github.com/finsberg/clang-format-docs

extra:
  recipe-maintainers:
    - finsberg
